//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://impl.endpoint.wsmefairhsp.mef.gob.pe/", ConfigurationName="WCF_AIRSH.WsmefairhspWs")]
    public interface WsmefairhspWs {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.genericOutputEmpleado consultaIndividual(string cod_tipo_documento, string numero_documento);
        
        // CODEGEN: El parámetro 'lista' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.consultaMasivaResponse consultaMasiva(APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.consultaMasivaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="response")]
        APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.genericOutputEmpleado consultaIndividualPorNombre(string nombre, string apellido_paterno, string apellido_materno);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.endpoint.wsmefairhsp.mef.gob.pe/")]
    public partial class genericOutputEmpleado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codMensajeField;
        
        private empleadoForm[] dataField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codMensaje {
            get {
                return this.codMensajeField;
            }
            set {
                this.codMensajeField = value;
                this.RaisePropertyChanged("codMensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public empleadoForm[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.endpoint.wsmefairhsp.mef.gob.pe/")]
    public partial class empleadoForm : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string codigoAirhspField;
        
        private string codigoCargoFuncionalField;
        
        private string codigoGrupoOcupacionalField;
        
        private string codigoNivelGobiernoField;
        
        private string codigoPliegoField;
        
        private string codigoRegimenLaboralField;
        
        private string codigoRegimenPensionarioField;
        
        private string codigoSectorField;
        
        private string codigoTipoDocumentoIdentidadField;
        
        private string codigoTipoPersonaField;
        
        private string codigoUnidadEjecutoraField;
        
        private string descripcionCargoFuncionalField;
        
        private string descripcionGrupoOcupacionalField;
        
        private string descripcionNivelGobiernoField;
        
        private string descripcionPliegoField;
        
        private string descripcionRegimenLaboralField;
        
        private string descripcionRegimenPensionarioField;
        
        private string descripcionSectorField;
        
        private string descripcionTipoDocumentoIdentidadField;
        
        private string descripcionTipoPersonaField;
        
        private string descripcionUnidadEjecutoraField;
        
        private string estadoEmpleadoField;
        
        private string fechaCeseField;
        
        private string fechaIngresoField;
        
        private string nombresField;
        
        private string numeroDocumentoIdentidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoAirhsp {
            get {
                return this.codigoAirhspField;
            }
            set {
                this.codigoAirhspField = value;
                this.RaisePropertyChanged("codigoAirhsp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string codigoCargoFuncional {
            get {
                return this.codigoCargoFuncionalField;
            }
            set {
                this.codigoCargoFuncionalField = value;
                this.RaisePropertyChanged("codigoCargoFuncional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string codigoGrupoOcupacional {
            get {
                return this.codigoGrupoOcupacionalField;
            }
            set {
                this.codigoGrupoOcupacionalField = value;
                this.RaisePropertyChanged("codigoGrupoOcupacional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string codigoNivelGobierno {
            get {
                return this.codigoNivelGobiernoField;
            }
            set {
                this.codigoNivelGobiernoField = value;
                this.RaisePropertyChanged("codigoNivelGobierno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string codigoPliego {
            get {
                return this.codigoPliegoField;
            }
            set {
                this.codigoPliegoField = value;
                this.RaisePropertyChanged("codigoPliego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string codigoRegimenLaboral {
            get {
                return this.codigoRegimenLaboralField;
            }
            set {
                this.codigoRegimenLaboralField = value;
                this.RaisePropertyChanged("codigoRegimenLaboral");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string codigoRegimenPensionario {
            get {
                return this.codigoRegimenPensionarioField;
            }
            set {
                this.codigoRegimenPensionarioField = value;
                this.RaisePropertyChanged("codigoRegimenPensionario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string codigoSector {
            get {
                return this.codigoSectorField;
            }
            set {
                this.codigoSectorField = value;
                this.RaisePropertyChanged("codigoSector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string codigoTipoDocumentoIdentidad {
            get {
                return this.codigoTipoDocumentoIdentidadField;
            }
            set {
                this.codigoTipoDocumentoIdentidadField = value;
                this.RaisePropertyChanged("codigoTipoDocumentoIdentidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string codigoTipoPersona {
            get {
                return this.codigoTipoPersonaField;
            }
            set {
                this.codigoTipoPersonaField = value;
                this.RaisePropertyChanged("codigoTipoPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string codigoUnidadEjecutora {
            get {
                return this.codigoUnidadEjecutoraField;
            }
            set {
                this.codigoUnidadEjecutoraField = value;
                this.RaisePropertyChanged("codigoUnidadEjecutora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string descripcionCargoFuncional {
            get {
                return this.descripcionCargoFuncionalField;
            }
            set {
                this.descripcionCargoFuncionalField = value;
                this.RaisePropertyChanged("descripcionCargoFuncional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string descripcionGrupoOcupacional {
            get {
                return this.descripcionGrupoOcupacionalField;
            }
            set {
                this.descripcionGrupoOcupacionalField = value;
                this.RaisePropertyChanged("descripcionGrupoOcupacional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string descripcionNivelGobierno {
            get {
                return this.descripcionNivelGobiernoField;
            }
            set {
                this.descripcionNivelGobiernoField = value;
                this.RaisePropertyChanged("descripcionNivelGobierno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string descripcionPliego {
            get {
                return this.descripcionPliegoField;
            }
            set {
                this.descripcionPliegoField = value;
                this.RaisePropertyChanged("descripcionPliego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string descripcionRegimenLaboral {
            get {
                return this.descripcionRegimenLaboralField;
            }
            set {
                this.descripcionRegimenLaboralField = value;
                this.RaisePropertyChanged("descripcionRegimenLaboral");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string descripcionRegimenPensionario {
            get {
                return this.descripcionRegimenPensionarioField;
            }
            set {
                this.descripcionRegimenPensionarioField = value;
                this.RaisePropertyChanged("descripcionRegimenPensionario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string descripcionSector {
            get {
                return this.descripcionSectorField;
            }
            set {
                this.descripcionSectorField = value;
                this.RaisePropertyChanged("descripcionSector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string descripcionTipoDocumentoIdentidad {
            get {
                return this.descripcionTipoDocumentoIdentidadField;
            }
            set {
                this.descripcionTipoDocumentoIdentidadField = value;
                this.RaisePropertyChanged("descripcionTipoDocumentoIdentidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string descripcionTipoPersona {
            get {
                return this.descripcionTipoPersonaField;
            }
            set {
                this.descripcionTipoPersonaField = value;
                this.RaisePropertyChanged("descripcionTipoPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string descripcionUnidadEjecutora {
            get {
                return this.descripcionUnidadEjecutoraField;
            }
            set {
                this.descripcionUnidadEjecutoraField = value;
                this.RaisePropertyChanged("descripcionUnidadEjecutora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string estadoEmpleado {
            get {
                return this.estadoEmpleadoField;
            }
            set {
                this.estadoEmpleadoField = value;
                this.RaisePropertyChanged("estadoEmpleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string fechaCese {
            get {
                return this.fechaCeseField;
            }
            set {
                this.fechaCeseField = value;
                this.RaisePropertyChanged("fechaCese");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string fechaIngreso {
            get {
                return this.fechaIngresoField;
            }
            set {
                this.fechaIngresoField = value;
                this.RaisePropertyChanged("fechaIngreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string numeroDocumentoIdentidad {
            get {
                return this.numeroDocumentoIdentidadField;
            }
            set {
                this.numeroDocumentoIdentidadField = value;
                this.RaisePropertyChanged("numeroDocumentoIdentidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.endpoint.wsmefairhsp.mef.gob.pe/")]
    public partial class empleadoMasivoForm : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string codigoAirhspField;
        
        private string codigoCargoFuncionalField;
        
        private string codigoGrupoOcupacionalField;
        
        private string codigoMensajeField;
        
        private string codigoNivelGobiernoField;
        
        private string codigoPliegoField;
        
        private string codigoRegimenLaboralField;
        
        private string codigoRegimenPensionarioField;
        
        private string codigoSectorField;
        
        private string codigoTipoDocumentoIdentidadField;
        
        private string codigoTipoPersonaField;
        
        private string codigoUnidadEjecutoraField;
        
        private string descripcionCargoFuncionalField;
        
        private string descripcionGrupoOcupacionalField;
        
        private string descripcionMensajeField;
        
        private string descripcionNivelGobiernoField;
        
        private string descripcionPliegoField;
        
        private string descripcionRegimenLaboralField;
        
        private string descripcionRegimenPensionarioField;
        
        private string descripcionSectorField;
        
        private string descripcionTipoDocumentoIdentidadField;
        
        private string descripcionTipoPersonaField;
        
        private string descripcionUnidadEjecutoraField;
        
        private string estadoEmpleadoField;
        
        private string fechaCeseField;
        
        private string fechaIngresoField;
        
        private string nombresField;
        
        private string numeroDocumentoIdentidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string codigoAirhsp {
            get {
                return this.codigoAirhspField;
            }
            set {
                this.codigoAirhspField = value;
                this.RaisePropertyChanged("codigoAirhsp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string codigoCargoFuncional {
            get {
                return this.codigoCargoFuncionalField;
            }
            set {
                this.codigoCargoFuncionalField = value;
                this.RaisePropertyChanged("codigoCargoFuncional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string codigoGrupoOcupacional {
            get {
                return this.codigoGrupoOcupacionalField;
            }
            set {
                this.codigoGrupoOcupacionalField = value;
                this.RaisePropertyChanged("codigoGrupoOcupacional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string codigoMensaje {
            get {
                return this.codigoMensajeField;
            }
            set {
                this.codigoMensajeField = value;
                this.RaisePropertyChanged("codigoMensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string codigoNivelGobierno {
            get {
                return this.codigoNivelGobiernoField;
            }
            set {
                this.codigoNivelGobiernoField = value;
                this.RaisePropertyChanged("codigoNivelGobierno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string codigoPliego {
            get {
                return this.codigoPliegoField;
            }
            set {
                this.codigoPliegoField = value;
                this.RaisePropertyChanged("codigoPliego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string codigoRegimenLaboral {
            get {
                return this.codigoRegimenLaboralField;
            }
            set {
                this.codigoRegimenLaboralField = value;
                this.RaisePropertyChanged("codigoRegimenLaboral");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string codigoRegimenPensionario {
            get {
                return this.codigoRegimenPensionarioField;
            }
            set {
                this.codigoRegimenPensionarioField = value;
                this.RaisePropertyChanged("codigoRegimenPensionario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string codigoSector {
            get {
                return this.codigoSectorField;
            }
            set {
                this.codigoSectorField = value;
                this.RaisePropertyChanged("codigoSector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string codigoTipoDocumentoIdentidad {
            get {
                return this.codigoTipoDocumentoIdentidadField;
            }
            set {
                this.codigoTipoDocumentoIdentidadField = value;
                this.RaisePropertyChanged("codigoTipoDocumentoIdentidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string codigoTipoPersona {
            get {
                return this.codigoTipoPersonaField;
            }
            set {
                this.codigoTipoPersonaField = value;
                this.RaisePropertyChanged("codigoTipoPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string codigoUnidadEjecutora {
            get {
                return this.codigoUnidadEjecutoraField;
            }
            set {
                this.codigoUnidadEjecutoraField = value;
                this.RaisePropertyChanged("codigoUnidadEjecutora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string descripcionCargoFuncional {
            get {
                return this.descripcionCargoFuncionalField;
            }
            set {
                this.descripcionCargoFuncionalField = value;
                this.RaisePropertyChanged("descripcionCargoFuncional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string descripcionGrupoOcupacional {
            get {
                return this.descripcionGrupoOcupacionalField;
            }
            set {
                this.descripcionGrupoOcupacionalField = value;
                this.RaisePropertyChanged("descripcionGrupoOcupacional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string descripcionMensaje {
            get {
                return this.descripcionMensajeField;
            }
            set {
                this.descripcionMensajeField = value;
                this.RaisePropertyChanged("descripcionMensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string descripcionNivelGobierno {
            get {
                return this.descripcionNivelGobiernoField;
            }
            set {
                this.descripcionNivelGobiernoField = value;
                this.RaisePropertyChanged("descripcionNivelGobierno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string descripcionPliego {
            get {
                return this.descripcionPliegoField;
            }
            set {
                this.descripcionPliegoField = value;
                this.RaisePropertyChanged("descripcionPliego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string descripcionRegimenLaboral {
            get {
                return this.descripcionRegimenLaboralField;
            }
            set {
                this.descripcionRegimenLaboralField = value;
                this.RaisePropertyChanged("descripcionRegimenLaboral");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string descripcionRegimenPensionario {
            get {
                return this.descripcionRegimenPensionarioField;
            }
            set {
                this.descripcionRegimenPensionarioField = value;
                this.RaisePropertyChanged("descripcionRegimenPensionario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string descripcionSector {
            get {
                return this.descripcionSectorField;
            }
            set {
                this.descripcionSectorField = value;
                this.RaisePropertyChanged("descripcionSector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string descripcionTipoDocumentoIdentidad {
            get {
                return this.descripcionTipoDocumentoIdentidadField;
            }
            set {
                this.descripcionTipoDocumentoIdentidadField = value;
                this.RaisePropertyChanged("descripcionTipoDocumentoIdentidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string descripcionTipoPersona {
            get {
                return this.descripcionTipoPersonaField;
            }
            set {
                this.descripcionTipoPersonaField = value;
                this.RaisePropertyChanged("descripcionTipoPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string descripcionUnidadEjecutora {
            get {
                return this.descripcionUnidadEjecutoraField;
            }
            set {
                this.descripcionUnidadEjecutoraField = value;
                this.RaisePropertyChanged("descripcionUnidadEjecutora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string estadoEmpleado {
            get {
                return this.estadoEmpleadoField;
            }
            set {
                this.estadoEmpleadoField = value;
                this.RaisePropertyChanged("estadoEmpleado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string fechaCese {
            get {
                return this.fechaCeseField;
            }
            set {
                this.fechaCeseField = value;
                this.RaisePropertyChanged("fechaCese");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string fechaIngreso {
            get {
                return this.fechaIngresoField;
            }
            set {
                this.fechaIngresoField = value;
                this.RaisePropertyChanged("fechaIngreso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string numeroDocumentoIdentidad {
            get {
                return this.numeroDocumentoIdentidadField;
            }
            set {
                this.numeroDocumentoIdentidadField = value;
                this.RaisePropertyChanged("numeroDocumentoIdentidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.endpoint.wsmefairhsp.mef.gob.pe/")]
    public partial class respuestaForm : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoMensajeField;
        
        private string codigoTipoDocumentoField;
        
        private string descripcionMensajeField;
        
        private string numeroDocumentoField;
        
        private int numeroFilaField;
        
        private bool numeroFilaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoMensaje {
            get {
                return this.codigoMensajeField;
            }
            set {
                this.codigoMensajeField = value;
                this.RaisePropertyChanged("codigoMensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoTipoDocumento {
            get {
                return this.codigoTipoDocumentoField;
            }
            set {
                this.codigoTipoDocumentoField = value;
                this.RaisePropertyChanged("codigoTipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcionMensaje {
            get {
                return this.descripcionMensajeField;
            }
            set {
                this.descripcionMensajeField = value;
                this.RaisePropertyChanged("descripcionMensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("numeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int numeroFila {
            get {
                return this.numeroFilaField;
            }
            set {
                this.numeroFilaField = value;
                this.RaisePropertyChanged("numeroFila");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroFilaSpecified {
            get {
                return this.numeroFilaFieldSpecified;
            }
            set {
                this.numeroFilaFieldSpecified = value;
                this.RaisePropertyChanged("numeroFilaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.endpoint.wsmefairhsp.mef.gob.pe/")]
    public partial class genericOutputMasivo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool indicadorExitoField;
        
        private bool indicadorExitoFieldSpecified;
        
        private respuestaForm[] listaErroresField;
        
        private empleadoMasivoForm[] listaResultadosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool indicadorExito {
            get {
                return this.indicadorExitoField;
            }
            set {
                this.indicadorExitoField = value;
                this.RaisePropertyChanged("indicadorExito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indicadorExitoSpecified {
            get {
                return this.indicadorExitoFieldSpecified;
            }
            set {
                this.indicadorExitoFieldSpecified = value;
                this.RaisePropertyChanged("indicadorExitoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaErrores", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public respuestaForm[] listaErrores {
            get {
                return this.listaErroresField;
            }
            set {
                this.listaErroresField = value;
                this.RaisePropertyChanged("listaErrores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaResultados", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public empleadoMasivoForm[] listaResultados {
            get {
                return this.listaResultadosField;
            }
            set {
                this.listaResultadosField = value;
                this.RaisePropertyChanged("listaResultados");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://impl.endpoint.wsmefairhsp.mef.gob.pe/")]
    public partial class requestForm : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codTipoDocumentoField;
        
        private string numeroDocumentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codTipoDocumento {
            get {
                return this.codTipoDocumentoField;
            }
            set {
                this.codTipoDocumentoField = value;
                this.RaisePropertyChanged("codTipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("numeroDocumento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaMasiva", WrapperNamespace="http://impl.endpoint.wsmefairhsp.mef.gob.pe/", IsWrapped=true)]
    public partial class consultaMasivaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.requestForm[] lista;
        
        public consultaMasivaRequest() {
        }
        
        public consultaMasivaRequest(APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.requestForm[] lista) {
            this.lista = lista;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaMasivaResponse", WrapperNamespace="http://impl.endpoint.wsmefairhsp.mef.gob.pe/", IsWrapped=true)]
    public partial class consultaMasivaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.genericOutputMasivo response;
        
        public consultaMasivaResponse() {
        }
        
        public consultaMasivaResponse(APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.genericOutputMasivo response) {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsmefairhspWsChannel : APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.WsmefairhspWs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsmefairhspWsClient : System.ServiceModel.ClientBase<APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.WsmefairhspWs>, APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.WsmefairhspWs {
        
        public WsmefairhspWsClient() {
        }
        
        public WsmefairhspWsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsmefairhspWsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsmefairhspWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsmefairhspWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.genericOutputEmpleado consultaIndividual(string cod_tipo_documento, string numero_documento) {
            return base.Channel.consultaIndividual(cod_tipo_documento, numero_documento);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.consultaMasivaResponse APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.WsmefairhspWs.consultaMasiva(APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.consultaMasivaRequest request) {
            return base.Channel.consultaMasiva(request);
        }
        
        public APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.genericOutputMasivo consultaMasiva(APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.requestForm[] lista) {
            APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.consultaMasivaRequest inValue = new APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.consultaMasivaRequest();
            inValue.lista = lista;
            APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.consultaMasivaResponse retVal = ((APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.WsmefairhspWs)(this)).consultaMasiva(inValue);
            return retVal.response;
        }
        
        public APP.MEF.ADMINISTRAR.FAG.PAG.WCF_AIRSH.genericOutputEmpleado consultaIndividualPorNombre(string nombre, string apellido_paterno, string apellido_materno) {
            return base.Channel.consultaIndividualPorNombre(nombre, apellido_paterno, apellido_materno);
        }
    }
}
