
PROCEDURE PRC_PROXIMO_CONTRATO(
    PO_CURSOR OUT SYS_REFCURSOR 
) as
BEGIN
    OPEN PO_CURSOR FOR
    SELECT NVL(MAX(TO_NUMBER(C.ID_CONTRATO))+1,1) AS COD_CONTRATO FROM FAGPAC.T_FACPAG_M_CONTRATO C;
END;


/******************************************/

ALTER TABLE FAGPAC.T_FACPAG_M_CONTRATO ADD
    (
        ID_ARCHIVO_RNSDD NUMBER,
        ID_ARCHIVO_REDAM NUMBER,
        ID_ARCHIVO_REDERECI NUMBER,
        ID_ARCHIVO_AIRSHP NUMBER,
        ID_ARCHIVO_OTROS NUMBER,
        FLG_OTROS CHAR(1)
    );

/*******************************************/

PROCEDURE PRC_INSERT_CONTRATO(
        P_ID_CONTRATO       IN FAGPAC.T_FACPAG_M_CONTRATO.ID_CONTRATO%TYPE,
        --     P_ID_COORDINADOR              IN FAGPAC.T_FACPAG_M_CONTRATO.ID_COORDINADOR%TYPE,
        P_USUARIO_UPT       IN FAGPAC.T_FACPAG_M_CONTRATO.USUARIO_UPT%TYPE,
        P_ID_SOLICITUD      IN FAGPAC.T_FACPAG_M_CONTRATO.ID_SOLICITUD%TYPE,
        P_ID_ARCHIVO        IN FAGPAC.T_FACPAG_M_CONTRATO.ID_ARCHIVO%TYPE,
        P_USUARIO           IN FAGPAC.T_FACPAG_M_CONTRATO.USU_INGRESO%TYPE,
        P_IP                IN FAGPAC.T_FACPAG_M_CONTRATO.IP_INGRESO%TYPE,
        P_NUM_CONTRATO      IN FAGPAC.T_FACPAG_M_CONTRATO.NUM_CONTRATO%TYPE,
        P_ID_ARCHIVO_RNSDD  IN FAGPAC.T_FACPAG_M_CONTRATO.ID_ARCHIVO_RNSDD%TYPE,
        P_ID_ARCHIVO_REDAM  IN FAGPAC.T_FACPAG_M_CONTRATO.ID_ARCHIVO_REDAM%TYPE,
        P_ID_ARCHIVO_REDERECI   IN FAGPAC.T_FACPAG_M_CONTRATO.ID_ARCHIVO_REDERECI%TYPE,
        P_ID_ARCHIVO_AIRSHP IN FAGPAC.T_FACPAG_M_CONTRATO.ID_ARCHIVO_AIRSHP%TYPE,
        P_ID_ARCHIVO_OTROS  IN FAGPAC.T_FACPAG_M_CONTRATO.ID_ARCHIVO_OTROS%TYPE,
        
        P_FLG_OTROS         IN FAGPAC.T_FACPAG_M_CONTRATO.FLG_OTROS%TYPE,
        P_FLG_HIST          IN VARCHAR2
        
    ) AS
    BEGIN
    /*=====================================================================================
        OBJETIVO            : UPDATE DE LA TABLA FAGPAC.T_FACPAG_M_CONTRATO (INSERT)
        PARAMETROS          : -
        AUTOR               : MORALES MAGUIÑA MIGUEL
        FECHA CREACION      : 17/06/2022
        FECHA MODIFICACION  :
        COMENTARIOS         :
        ///////////MODIFICACIONES ///////////
        FECHA    AUTOR           MOTIVO
        05022024 KAREN CARRANZA  CAMBIO DE NUM CONTRATO A CORRELATIVO 
    =====================================================================================*/
            
    --  ACTUALIZAR REGISTROS
        INSERT INTO FAGPAC.T_FACPAG_M_CONTRATO(
            ID_CONTRATO
            ,ID_COORDINADOR
            ,USUARIO_UPT
            ,ID_PERSONAL
            ,ID_ENTIDAD
            ,TIPO_PROCESO
            ,ID_SOLICITUD
            ,NUM_CONTRATO
            ,ANIO_CONTRATO
            ,ESTADO_CONT
            ,MONTO_MENSUAL
            ,FECHA_INICIO
            ,FECHA_FIN
            ,ID_ARCHIVO
            ,FEC_INGRESO
            ,IP_INGRESO
            ,USU_INGRESO
            ,FLG_RNSDD
            ,FLG_REDAM
            ,FLG_REDERECI
            ,FLG_AIRSHP
            ,ID_ARCHIVO_RNSDD
            ,ID_ARCHIVO_REDAM
            ,ID_ARCHIVO_REDERECI
            ,ID_ARCHIVO_AIRSHP
            ,ID_ARCHIVO_OTROS
            ,FLG_OTROS
        )
        SELECT
            (SELECT NVL(MAX(TO_NUMBER(C.ID_CONTRATO))+1,1) FROM FAGPAC.T_FACPAG_M_CONTRATO C),
            (SELECT CO.ID_COORDINADOR FROM FAGPAC.T_FACPAG_M_COORDINADORES CO WHERE CO.USUARIO=S.USER_COORDINADOR AND FLG_SOLICITUD='1' and rownum=1) P_ID_COORDINADOR,
            -- (SELECT CO.ID_COORDINADOR FROM FAGPAC.T_FACPAG_M_COORDINADORES CO WHERE CO.USUARIO=S.USER_COORDINADOR AND FLG_ESTADO='1') P_ID_COORDINADOR,
            P_USUARIO_UPT,
            S.ID_PERSONAL,
            S.ID_ENTIDAD,
            S.TIPO_PROCESO,
            P_ID_SOLICITUD,
            --P_NUM_CONTRATO,--(SELECT NVL(MAX(TO_NUMBER(CC.NUM_CONTRATO))+1,1) FROM FAGPAC.T_FACPAG_M_CONTRATO CC WHERE CC.ANIO_CONTRATO=TO_CHAR(SYSDATE, 'YYYY')),
            CASE (P_FLG_HIST) WHEN 'N' THEN (SELECT NVL(MAX(TO_NUMBER(CC.NUM_CONTRATO))+1,1) FROM FAGPAC.T_FACPAG_M_CONTRATO CC WHERE CC.ANIO_CONTRATO=TO_CHAR(SYSDATE, 'YYYY') AND CC.ID_ENTIDAD=S.ID_ENTIDAD) ELSE P_NUM_CONTRATO END,
            TO_CHAR(SYSDATE, 'YYYY'),
            'V',
            S.MONTO_RECIBO,
            S.FECHA_INICIO,
            S.FECHA_FIN,
            P_ID_ARCHIVO,
            SYSDATE,
            P_IP,
            P_USUARIO,
            '1',
            '1',
            '1',
            '1',
            P_ID_ARCHIVO_RNSDD,
            P_ID_ARCHIVO_REDAM,
            P_ID_ARCHIVO_REDERECI,
            P_ID_ARCHIVO_AIRSHP,
            P_ID_ARCHIVO_OTROS,
            FLG_OTROS
        FROM FAGPAC.V_LISTA_PERSONAL_SOLICITUD S
                WHERE   S.ID_SOLICITUD = P_ID_SOLICITUD AND S.FLG_ESTADO='1';
                UPDATE FAGPAC.T_FACPAG_M_SOLICITUD SET USU_MODIFICA=P_USUARIO,IP_MODIFICA=P_IP,FEC_MODIFICA=SYSDATE, IDEDOCODIGO='007',FECHA_APROBADO_UTP=SYSDATE WHERE ID_SOLICITUD=P_ID_SOLICITUD;
    END PRC_INSERT_CONTRATO;