
  CREATE OR REPLACE FORCE VIEW "FAGPAC"."V_LISTA_PERSONAL_SOLICITUD" ("ID_SOLICITUD", "APELLIDO_PATERNO", "APELLIDO_MATERNO", "NOMBRES", "NUM_DOCUMENTO", "RUC", "COD_DEPA", "COD_PROV", "COD_DIST", "FEC_REGI_SOLICITUD", "FLG_ESTADO", "DENOMINACION_PUESTO", "ID_PERSONAL", "ENTIDAD", "ENTIDAD_PADRE", "FLG_ENVIO_PROPUESTA", "MONTO_RECIBO", "FLG_CHECK_4", "MONTO_MENSUAL", "FECHA_INICIO", "FECHA_FIN", "DESC_PROCESO", "TIPO_PROCESO", "FLG_PENSIONISTA_POLICIA", "FLG_PENSIONISTA_ESTADO", "FLG_TERMINOS", "USER_COORDINADOR", "TELEFONO", "EMAIL", "DIRECCION", "ID_ENTIDAD", "NUM_PROCESO", "ANIO_PROCESO", "IDEDOCODIGO", "RUC_ENTIDAD", "DIRECCION_ENTIDAD", "COD_DEPA_ENTIDAD", "COD_PROV_ENTIDAD", "COD_DIST_ENTIDAD", "REPRESENTANTE", "TIPO_RESOLUCION", "NUMERO_RESOLUCION", "CARGO_AUTORIDAD", "DNI_AUTORIDAD", "FECHA_ENVIO_UTP", "FECHA_APROBADO_UTP", "FLG_ANEXO1", "FLG_ANEXO2", "FLG_ANEXO3", "FLG_ANEXO4", "FLG_ANEXO5", "FLG_ANEXO7", "FLG_BANCO", "FLG_H_PROFESIONAL", "FLG_OTROS", "FLG_INFORME_F", "FLG_DATOS_SECTOR", "FLG_FORMATOA", "FLG_FORMATOB", "FLG_FORMATOC", "FLG_FORMATOD", "FLG_FORMATOE", "FLG_FORMATOH", "FLG_PAC_ANEXO2", "FLG_PAC_H_PROFESIONAL", "ID_ANEXO1", "ID_ANEXO2", "ID_ANEXO3", "ID_ANEXO4", "ID_ANEXO5", "ID_ANEXO7", "ID_BANCO", "ID_H_PROFESIONAL", "ID_OTROS", "ID_INFORME_F", "ID_DATOS_SECTOR", "ID_FORMATOA", "ID_FORMATOB", "ID_FORMATOC", "ID_FORMATOD", "ID_FORMATOE", "ID_FORMATOH", "ID_PAC_ANEXO2", "ID_PAC_H_PROFESIONAL", "FLG_CUMPLE_REQUISITOS_UTP", "ID_ARCHIVO_CONTRATO", "FLG_CALIFICA_REQUISITOS_UTP", "NUM_CONTRATO", "ANIO_CONTRATO", "ID_CONTRATO", "ARCHIVO_TDR", "ACRONIMO", "NR_TRAMITE", "FLG_PENSIONES", "ARCHIVO_PUESTO_SUS_SOLICITUD", "NUM_CONTRATO_TEXT") AS 
  SELECT
SP.ID_SOLICITUD
,P.APELLIDO_PATERNO
,P.APELLIDO_MATERNO
,P.NOMBRES
,P.NUM_DOCUMENTO
,P.RUC
,P.COD_DEPA
,P.COD_PROV
,P.COD_DIST
,SP.FEC_REGI_SOLICITUD
,SP.FLG_ESTADO
,SP.DENOMINACION_PUESTO
,SP.ID_PERSONAL
,CASE WHEN E.ID_PADRE_ENTIDAD > 0 THEN ES.DESC_ENTIDAD /*|| ' - ' || E.DESC_ENTIDAD*/  ELSE E.DESC_ENTIDAD END ENTIDAD
,CASE WHEN E.ID_PADRE_ENTIDAD > 0 THEN ES.DESC_ENTIDAD ELSE E.DESC_ENTIDAD END ENTIDAD_PADRE
,NVL(SP.FLG_ENVIO_PROPUESTA,0) FLG_ENVIO_PROPUESTA
,SP.MONTO_RECIBO
,SP.FLG_CHECK_4
,S.MONTO_MENSUAL
,S.FECHA_INICIO
,S.FECHA_FIN
,CASE WHEN S.TIPO_PROCESO ='F' THEN 'FAG LEY N° 25650' ELSE  'PAC LEY N° 29806' END DESC_PROCESO
,S.TIPO_PROCESO
,SP.FLG_PENSIONISTA_POLICIA
,SP.FLG_PENSIONISTA_ESTADO
,SP.FLG_TERMINOS
,SP.USU_INGRESO AS USER_COORDINADOR
,P.TELEFONO
,P.EMAIL
,P.DIRECCION
,S.ID_ENTIDAD
,S.NUM_PROCESO
,S.ANIO_PROCESO
,S.IDEDOCODIGO
,E.RUC AS RUC_ENTIDAD
,E.DIRECCION  AS DIRECCION_ENTIDAD
,E.COD_DEPA AS COD_DEPA_ENTIDAD
,E.COD_PROV AS COD_PROV_ENTIDAD
,E.COD_DIST AS COD_DIST_ENTIDAD
,E.REPRESENTANTE
,E.TIPO_RESOLUCION
,E.NUMERO_RESOLUCION
,E.CARGO_AUTORIDAD
,E.DNI_AUTORIDAD
,S.FECHA_ENVIO_UTP
,S.FECHA_APROBADO_UTP
,SP.FLG_ANEXO1
,SP.FLG_ANEXO2
,SP.FLG_ANEXO3
,SP.FLG_ANEXO4
,SP.FLG_ANEXO5
,SP.FLG_ANEXO7
,SP.FLG_BANCO
,SP.FLG_H_PROFESIONAL
,SP.FLG_OTROS
,SP.FLG_INFORME_F
,SP.FLG_DATOS_SECTOR
,SP.FLG_FORMATOA
,SP.FLG_FORMATOB
,SP.FLG_FORMATOC
,SP.FLG_FORMATOD
,SP.FLG_FORMATOE
,SP.FLG_FORMATOH
,SP.FLG_PAC_ANEXO2
,SP.FLG_PAC_H_PROFESIONAL
,S.ID_ANEXO1
,S.ID_ANEXO2
,S.ID_ANEXO3
,S.ID_ANEXO4
,S.ID_ANEXO5
,S.ID_ANEXO7
,S.ID_BANCO
,S.ID_H_PROFESIONAL
,S.ID_OTROS
,S.ID_INFORME_F
,S.ID_DATOS_SECTOR
,S.ID_FORMATOA
,S.ID_FORMATOB
,S.ID_FORMATOC
,S.ID_FORMATOD
,S.ID_FORMATOE
,S.ID_FORMATOH
,S.ID_PAC_ANEXO2
,S.ID_PAC_H_PROFESIONAL
,S.FLG_CUMPLE_REQUISITOS_UTP
,CON.ID_ARCHIVO ID_ARCHIVO_CONTRATO
,S.FLG_CALIFICA_REQUISITOS_UTP
,CON.NUM_CONTRATO
,CON.ANIO_CONTRATO
,CON.ID_CONTRATO
,S.ARCHIVO_TDR
,NVL(ES.ACRONIMO,E.ACRONIMO) ACRONIMO
,S.NR_TRAMITE
,SP.FLG_PENSIONES
,S.ARCHIVO_PUESTO_SUS_SOLICITUD
,CON.NUM_CONTRATO ||'-'|| CON.ANIO_CONTRATO || '-' || CASE WHEN S.TIPO_PROCESO ='F' THEN 'FAG' ELSE  'PAC' END  || '-' || NVL(ES.ACRONIMO,E.ACRONIMO) NUM_CONTRATO_TEXT
FROM FAGPAC.T_FACPAG_J_SOLI_PERSONAL  SP
INNER JOIN FAGPAC.T_FACPAG_M_SOLICITUD S
ON SP.ID_SOLICITUD=S.ID_SOLICITUD AND S.FLG_ESTADO='1'
INNER JOIN FAGPAC.T_FACPAG_M_PERSONAL P
ON SP.ID_PERSONAL=P.ID_PERSONAL
INNER JOIN FAGPAC.T_FACPAG_L_ENTIDADES E
ON S.ID_ENTIDAD=E.ID_ENTIDAD
LEFT JOIN FAGPAC.T_FACPAG_M_CONTRATO CON
ON CON.ID_SOLICITUD=S.ID_SOLICITUD
LEFT JOIN FAGPAC.T_FACPAG_L_ENTIDADES ES
ON ES.ID_ENTIDAD=E.ID_PADRE_ENTIDAD
;

