//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/ws", ConfigurationName="WCF_DatosPersonales.ReniecSoap")]
    public interface ReniecSoap {
        
        // CODEGEN: El parámetro 'TDniResult' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ws/TDni", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.TDniResponse TDni(APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.TDniRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/ws/TDni", ReplyAction="*")]
        System.Threading.Tasks.Task<APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.TDniResponse> TDniAsync(APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.TDniRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/ws")]
    public partial class tabla : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string t00Field;
        
        private string t01Field;
        
        private string t02Field;
        
        private string t03Field;
        
        private string t04Field;
        
        private string t05Field;
        
        private string t06Field;
        
        private string t07Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string t00 {
            get {
                return this.t00Field;
            }
            set {
                this.t00Field = value;
                this.RaisePropertyChanged("t00");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string t01 {
            get {
                return this.t01Field;
            }
            set {
                this.t01Field = value;
                this.RaisePropertyChanged("t01");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string t02 {
            get {
                return this.t02Field;
            }
            set {
                this.t02Field = value;
                this.RaisePropertyChanged("t02");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string t03 {
            get {
                return this.t03Field;
            }
            set {
                this.t03Field = value;
                this.RaisePropertyChanged("t03");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string t04 {
            get {
                return this.t04Field;
            }
            set {
                this.t04Field = value;
                this.RaisePropertyChanged("t04");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string t05 {
            get {
                return this.t05Field;
            }
            set {
                this.t05Field = value;
                this.RaisePropertyChanged("t05");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string t06 {
            get {
                return this.t06Field;
            }
            set {
                this.t06Field = value;
                this.RaisePropertyChanged("t06");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string t07 {
            get {
                return this.t07Field;
            }
            set {
                this.t07Field = value;
                this.RaisePropertyChanged("t07");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TDni", WrapperNamespace="http://localhost/ws", IsWrapped=true)]
    public partial class TDniRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/ws", Order=0)]
        public string NoDNI;
        
        public TDniRequest() {
        }
        
        public TDniRequest(string NoDNI) {
            this.NoDNI = NoDNI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TDniResponse", WrapperNamespace="http://localhost/ws", IsWrapped=true)]
    public partial class TDniResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/ws", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.tabla[] TDniResult;
        
        public TDniResponse() {
        }
        
        public TDniResponse(APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.tabla[] TDniResult) {
            this.TDniResult = TDniResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReniecSoapChannel : APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.ReniecSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReniecSoapClient : System.ServiceModel.ClientBase<APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.ReniecSoap>, APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.ReniecSoap {
        
        public ReniecSoapClient() {
        }
        
        public ReniecSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReniecSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReniecSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReniecSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.TDniResponse APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.ReniecSoap.TDni(APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.TDniRequest request) {
            return base.Channel.TDni(request);
        }
        
        public APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.tabla[] TDni(string NoDNI) {
            APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.TDniRequest inValue = new APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.TDniRequest();
            inValue.NoDNI = NoDNI;
            APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.TDniResponse retVal = ((APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.ReniecSoap)(this)).TDni(inValue);
            return retVal.TDniResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.TDniResponse> APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.ReniecSoap.TDniAsync(APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.TDniRequest request) {
            return base.Channel.TDniAsync(request);
        }
        
        public System.Threading.Tasks.Task<APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.TDniResponse> TDniAsync(string NoDNI) {
            APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.TDniRequest inValue = new APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.TDniRequest();
            inValue.NoDNI = NoDNI;
            return ((APP.MEF.ADMINISTRAR.FAG.PAG.WCF_DatosPersonales.ReniecSoap)(this)).TDniAsync(inValue);
        }
    }
}
